version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
      - aiden-dev
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318"     # OTLP HTTP receiver
      - "8888:8888"     # Prometheus metrics exporter
      - "14268:14268"   # Jaeger Thrift receiver for traces
      - "9200:9200"     # Elasticsearch

networks:
  aiden-dev:
    name: aiden-dev