version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    network_mode: "host"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    # ports:
    #   - "4317:4317"     # OTLP gRPC receiver
    #   - "4318:4318"     # OTLP HTTP receiver
    #   - "8889:8889"     # Prometheus metrics exporter
    #   - "14268:14268"   # Jaeger Thrift receiver for traces
    #   - "9200:9200"     # Elasticsearch

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # ports:
    #   - "9090:9090"     # Prometheus web interface
    network_mode: "host"
    depends_on:
      - otel-collector

  jaeger:
    image: jaegertracing/all-in-one:1.60
    container_name: jaeger
    command: ["--collector.otlp.enabled=false"]
    # environment:
    #   - METRICS_STORAGE_TYPE=prometheus
    #   - PROMETHEUS_SERVER_URL=http://localhost:9090
    # ports:
    #   - "5775:5775"    # Zipkin Thrift compact protocol
    #   - "5778:5778"    # Zipkin HTTP server
    #   - "14250:14250"  # gRPC
    #   - "14268:14268"  # HTTP
    #   - "14250:14250"  # gRPC
    #   - "14267:14267"  # HTTP
    #   - "14399:14399"  # JAEGER_QUERY_PORT
    #   - "16686:16686"  # Jaeger UI
    #   - "14250:14250"  # Jaeger gRPC
    #   - "14268:14268"  # Jaeger HTTP
    #   - "5778:5778"    # Jaeger Admin
    #   - "44317:44317"   # Onboard Otel Collector
    network_mode: "host"
    depends_on:
      - otel-collector
      - prometheus

# networks:
#   aiden-dev:
#     name: aiden-dev