receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  logging:
    loglevel: debug

  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:

service:
    pipelines:
        logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging]
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging]
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging, prometheus]
