# prometheus.yml
global:
  scrape_interval: 15s  # How often to scrape metrics from targets
  evaluation_interval: 15s  # How often to evaluate rules

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]