{
 "title": "Home Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "aiden_ram_percent_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "aiden_cpu_percent_ratio{cpu_number=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aiden_cpu_percent_ratio{cpu_number=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aiden_cpu_percent_ratio{cpu_number=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aiden_cpu_percent_ratio{cpu_number=\"3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aiden_service_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "aiden_service_latency_seconds_sum",
     "legendFormat": "__auto"
    },
    {
     "expr": "aiden_service_latency_seconds_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "aiden_service_latency_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Errors Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aiden_service_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "operation": "http_request", "service": "aiden-api" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}