apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      timeField: '@timestamp'
