{
 "title": "AIden's Tool Server",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Metrics Datasource", "query": "prometheus" },
   { "name": "DS_JAEGER", "label": "Traces Datasource", "query": "jaeger" },
   { "name": "DS_ELASTICSEARCH", "label": "Logs Datasource", "query": "elasticsearch" }
  ]
 },
 "panels": [
  { "title": "Golden Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "aiden_service_latency_seconds_sum",
     "legendFormat": "__auto"
    },
    {
     "expr": "aiden_service_latency_seconds_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "aiden_service_latency_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aiden_service_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aiden_service_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Saturation | RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "aiden_ram_percent_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Saturation | CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "aiden_cpu_percent_ratio", "legendFormat": "__auto" },
    {
     "expr": "aiden_cpu_percent_ratio{cpu_number=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aiden_cpu_percent_ratio{cpu_number=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aiden_cpu_percent_ratio{cpu_number=\"3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logging and Tracing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "operation": "http_request", "service": "aiden-api" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}