{
 "title": "AIden's Vector Storage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Vector Storage Vitals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "app_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Recovery Mode",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "app_status_recovery_mode", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Vector Storage Collections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Collections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "collections_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total Vectors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "collections_vector_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Full Collections",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
     "targets": [
      { "expr": "collections_full_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Aggregated Collections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "collections_aggregated_total", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Vector Storage REST API Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true
  }
 ]
}